---
title: "Data Cleaning"
date: " 2021-01-26 (update: `r Sys.Date()`)"
output:
    html_document:
      theme: cerulean
      toc: yes
      toc_float: yes
editor_options:
  chunk_output_type: console
---


```{r}
library(data.table)
library(lubridate)
library(tidyverse)
library(dplyr)
```

## Load vaccine data

```{r}
dat <- readRDS(file = file.path("..", "tuann349_vad", "alldat.rds"))
load(file.path("..", "tuann349_vad", "vacinfo.Rdata"))
names(vacinfo) <- c("vacname2", "epi", "shot", "start")

vaccine <- readRDS(file = file.path("..", "tuann349_vad", "vaccine.rds"))
load(file.path("..", "tuann349_vad", "vacinfo.Rdata"))

tmp1 <- merge(vaccine, vacname3[, c("vacname", "vacname2")], by = "vacname", all.x = TRUE, sort = FALSE)
tmp2 <- tmp1[, .(province, district, commune, vacname, vacdate, shot = order(vacdate)), by = .(pid, vacname2)][order(pid, vacname2, shot)]
tab_vaccine_shot <- tmp2[, .N, by = .(vacname2, shot)][order(vacname2, shot)]
tab_vaccine_shot

# memory.limit(size=150000)

tmp1 <- merge(dat[(vacdate >= ymd("2017-01-01")) & (vacdate < ymd("2021-01-26")) & (vacdate >= dob) & (!vacname %in% c("BKT 0,1ml tu khoa (BCG)", "BKT 0.1ml (BCG)", "BKT 0.5 ml", "BKT 1 ml", "BKT 5 ml")), .(pid, province, district, commune, sex, dob, vacname, vacdate)],
              vacname3[, c("vacname", "vacname2")], by = "vacname", all.x = TRUE, sort = FALSE)

tmp1 <- tmp1 %>% distinct(., pid, province, district, commune, vacname2, vacdate, .keep_all = TRUE)

# nrow(tmp1)
# 29993118

# Remove duplicate by vacname2
nodups_distinct <- tmp1 %>% distinct(., pid, province, district, commune, sex, dob, vacname2, vacdate, .keep_all = TRUE)

# nrow(nodups_distinct)
# [1] 29991641

cols <- c("pid", "province", "district", "commune", "sex", "dob", "vacname2", "vacdate")
dups2 <- tmp1[duplicated(tmp1[,..cols]) | duplicated(tmp1[,..cols], fromLast = T),]
dups2$type <- "Have a same vaccine in a same date in same province"
fwrite(x = dups2, file = file.path(outp, "error_duplicate2.csv"))


tmp2 <- nodups_distinct[!is.na(vacname2)] %>%
  group_by(pid, vacname2) %>%
  arrange(vacdate) %>%
  mutate(shot = 1:n()) %>%
  ungroup()

tmp3 <- merge(tmp2, vacname3[, c("vacname", "tub", "heb", "dip", "per", "tes", "hib", "pol", "msl", "rub", "jev")], by = "vacname", all.x = TRUE, sort = FALSE)


tmp1 <- merge(tmp3, vacinfo, by = c("vacname2", "shot"), all.x = TRUE, sort = FALSE)

rm(list = c("tmp2", "tmp3"))

gc()

library(data.table)
setDT(tmp1)

vaccine_vad <- tmp1[, .(pid, province, district, commune, sex, dob, vacname, vacname2, 
                        epi, tub, heb, dip, per, tes, hib, pol, msl, rub, jev, shot, start, vacdate, 
                        vyear = year(vacdate), 
                        vmonth = month(vacdate), 
                        vagem = as.period(interval(dob, vacdate), unit = 'month')$month,
                        vagem2 = ((vacdate - dob)/dyears(1)) * 12)][, 
                                                                     .(pid, province, district, commune, sex, dob, vacname, vacname2,
                                                                       epi, tub, heb, dip, per, tes, hib, pol, msl, rub, jev, shot, start, vacdate, 
                                                                       vyear, vmonth, vagem, vagem2,
                                                                       vdelay = vagem2 - start)][order(pid, vacdate)]
rm(list = c("tmp1"))
gc()
saveRDS(vaccine_vad, file = file.path(outp, "vaccine_vad.rds"))
# fwrite(x = vaccine_vad, file = file.path(data_path, "vaccine_vad.csv"))

measle <- vaccine_vad[msl == 1]
saveRDS(measle, file = file.path(outp, "measle.rds"))
# fwrite(x = measle, file = file.path(data_path, "measle.csv"))
rm(list = c("measle"))
gc()

diptheria <- vaccine_vad[dip == 1]
saveRDS(diptheria, file = file.path(outp, "diptheria.rds"))
# fwrite(x = diptheria, file = file.path(data_path, "diptheria.csv"))
rm(list = c("diptheria"))
gc()

tuberculosis <- vaccine_vad[tub == 1]
saveRDS(tuberculosis, file = file.path(outp, "tuberculosis.rds"))
# fwrite(x = tuberculosis, file = file.path(data_path, "tuberculosis.csv"))
rm(list = c("tuberculosis"))
gc()

hepatitisb <- vaccine_vad[heb == 1]
saveRDS(hepatitisb, file = file.path(outp, "hepatitisb.rds"))
# fwrite(x = hepatitisb, file = file.path(data_path, "hepatitisb.csv"))
rm(list = c("hepatitisb"))
gc()

polio <- vaccine_vad[pol == 1]
saveRDS(polio, file = file.path(outp, "polio.rds"))
# fwrite(x = polio, file = file.path(data_path, "polio.csv"))
rm(list = c("polio"))
gc()
```

