---
title: "Data Exploration"
date: ' 2020-01-29 (update: `r Sys.Date()`)'
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_float: yes
    keep_md: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r}
knitr::opts_chunk$set()

library(workflowr)
library(data.table)
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)
library(gt)
library(gtsummary)
library(ggridges)
```

## Quick look at individuals

```{r}
#error_datetime <- read.csv(file.path("..", "..", "tuann349_vad", "error_datetime.csv")) %>% as.data.frame()
#error_duplicate <- read.csv(file.path("..", "..", "tuann349_vad", "error_duplicate.csv")) %>% as.data.frame()
rm(list = ls(all.names = TRUE))

individual_private <- readRDS(file = file.path("..", "..", "tuann349_vad", "individual_private.rds")) %>% filter(year<=2020)

individual_private$year <- year(individual_private$dob)
individual_private$month <- month(individual_private$dob)
individual_private$week <- week(individual_private$dob)

#child_private <- individual_private %>% filter(year <= 2020 & year >= 2017)

individual_private_overall <- individual_private[, .N, by = .(year, month)]
individual_private_overall2 <- individual_private[, .N, by = .(year, month, week)]
individual_private_province <- individual_private[, .N, by = .(year, month, province)]
individual_private_province2 <- individual_private[, .N, by = .(year, month, week, province)]
individual_private_sex <- individual_private[, .N, by = .(year, month, sex)]
individual_private_sex2 <- individual_private[, .N, by = .(year, month, week, sex)]
individual_private_province_sex <- individual_private[, .N, by = .(year, month, province, sex)]
individual_private_province_sex2 <- individual_private[, .N, by = .(year, month, week, province, sex)]
 
save(individual_private_overall, individual_private_province, individual_private_sex, individual_private_province_sex, file = file.path("..", "..", "tuann349_vad", "individual_private.Rdata"))

tab_individual_private_sum <- tbl_summary(individual_private[, .(province, sex, factor(year))])

save(tab_individual_private_sum, file = file.path("..", "..", "tuann349_vad", "tab_individual_private.Rdata"))
```

## Quick look at vaccine shots

```{r}
vaccine_vad_private <- readRDS(file = file.path("..", "..", "updated_dataset", "vaccine_vad_private.rds"))

vaccine_overall_private <- vaccine_vad_private[, .N, by = .(vyear, vmonth)]
vaccine_overall_private2 <- vaccine_vad_private[, .N, by = .(vyear, vmonth, vweek)]

vaccine_schedule_private <- vaccine_vad_private[, .N, by = .(vsyear, vsmonth)]
vaccine_schedule_private2 <- vaccine_vad_private[, .N, by = .(vsyear, vsmonth, vsweek)]

vaccine_province_private <- vaccine_vad_private[, .N, by = .(vyear, vmonth, province)]

vaccine_vacname_private <- vaccine_vad_private[, .N, by = .(vyear, vmonth, vacname2)]
#vaccine_vacname_private2 <- vaccine_vad_private[, .N, by = .(vyear, vmonth, vweek, vacname2)]

vaccine_province_vacname_private <- vaccine_vad_private[, .N, by = .(vyear, vmonth, province, vacname2)]
#vaccine_province_vacname_private2 <- vaccine_vad_private[, .N, by = .(vyear, vmonth, vweek, province, vacname2)]

save(vaccine_overall_private, vaccine_province_private, vaccine_vacname_private, vaccine_province_vacname_private, file = file.path("..", "..", "updated_dataset", "vaccine_private_all.Rdata"))
 
tab_vac_sum_private_all <- tbl_summary(vaccine_vad_private[, .(province, vacname2, factor(vyear))])
save(tab_vac_sum_private_all, file = file.path("..", "..", "updated_dataset", "tab_vaccine_private_all.Rdata"))
```

```{r}
load(file.path("..", "..", "updated_dataset", "vaccine_private_all.Rdata"))
load(file.path("..", "..", "updated_dataset", "tab_vaccine_private_all.Rdata"))

load(file.path("..", "..", "tuann349_vad", "individual_private.Rdata"))
load(file.path("..", "..", "tuann349_vad", "tab_individual_private.Rdata"))
```

### Descriptive table

```{r}
tab_vac_sum_private_all
tab_individual_private_sum
```


### Overall

```{r}
ggplot(data = individual_private_overall, aes(x = factor(month), y = N/1000, color = factor(year))) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey90", color = "grey90", alpha = 0.015) +
  geom_point(size = 3) +
  geom_line(aes(group = year), size = 1.5) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of vaccination individuals at private clinics (x 10^3)", breaks = seq(from = 0, to = 150, by = 10)) +
  scale_color_discrete(name = "Year") +
  theme_bw() +
  ggtitle("Total number of vaccination individuals by month and year")
ggsave(filename = file.path("..", "figures", "individual_private_month_year.png"), width = 15, height = 10)
```

```{r}
ggplot(individual_private_overall, aes(month, N/1000, color = factor(year))) +
  geom_point(size=2) +
  geom_line(aes(group=year)) +
  geom_smooth () +
  #stat_smooth(method="loess", formula = y ~ x, colour="blue", size=0.5) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of vaccination individuals (x 10^3)", breaks = seq(from = 0, to = 150, by = 10)) +
  scale_color_discrete(name = "Year") +
  theme_bw() +
  facet_wrap(~ year, scale = "free_y") +
  ggtitle("Total number of vaccination individuals by month and year")
ggsave(filename = file.path("..", "figures", "individual_private_month_year3.png"), width = 15, height = 10)
```

```{r}
ggplot(data = vaccine_overall_private, aes(x = factor(vmonth), y = N/1000, color = factor(vyear))) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point(size = 3) +
  geom_line(aes(group = vyear), size = 1.5) +
  scale_x_discrete(name = "Month") +
  geom_smooth() +
  stat_smooth(method="loess", formula = y ~ x, colour="blue", size=1.5) +
  scale_y_continuous(name = "Number of shot (x 10^3)", breaks = seq(from = 50, to = 1600, by = 100)) +
  scale_color_discrete(name = "Year") +
  theme_bw() +
  ggtitle("Total number of vaccination shots by month and year at private clinics")
ggsave(filename = file.path("..", "figures", "vaccine_month_year_private_all.png"), width = 7, height = 5)
```

```{r}
ggplot(vaccine_overall_private, aes(vmonth, N/1000, color = factor(vyear))) +
  geom_point(size=3) +
  geom_line(aes(group=vyear)) +
  geom_smooth () + 
  stat_smooth(method="loess", formula = y ~ x, colour="blue", size=1) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot (x 10^3)") +
  scale_color_discrete(name = "Year") +
  theme_bw() +
  ggtitle("Total number of vaccination shots by month and year at private clinics") +
  facet_wrap(~ vyear, scale = "free_y")
ggsave(filename = file.path("..", "figures", "vaccine_month_year_private_all2.png"), width = 7, height = 5)
```

### By province

```{r}
ggplot(data = vaccine_province_private, aes(x = factor(vmonth), y = N/1000, color = factor(vyear))) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point() +
  geom_line(aes(group = vyear)) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot (x 10^3)") +
  scale_color_discrete(name = "Year") +
  facet_wrap(~ province, scale = "free_y") +
  theme_bw() +
  theme(legend.position = "bottom") +
  ggtitle("Number of vaccination shot in each province by month and year at private clinics")
ggsave(filename = file.path("..", "figures", "vaccine_province_year_private_all.png"), width = 10, height = 7)
```

### By vaccine

```{r}
ggplot(data = vaccine_vacname_private, aes(x = factor(vmonth), y = N/1000)) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point(aes(color = factor(vyear))) +
  geom_line(aes(group = vyear, color = factor(vyear))) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot (x 10^3)") +
  scale_color_discrete(name = "Year") +
  facet_wrap(~ vacname2, scale = "free_y") +
  theme_bw() +
  theme(legend.position = "bottom") +
  ggtitle("Total number of shots of each vaccine at private clinics by month and year")
ggsave(filename = file.path("..", "figures", "vaccine_month_year_vaccine_private_all.png"), width = 10, height = 7)
```

```{r}
vaccine_vad <- readRDS(file = file.path("..", "tuann349_vad", "vaccine_vad.rds")) %>% filter(!pid %in% error_datetime$pid & !pid %in% error_duplicate$pid)
vaccine_vad$vweek <- week(vaccine_vad$vacdate)
vaccine_vad$byear <- year(vaccine_vad$dob)
vaccine_vad$bmonth <- month(vaccine_vad$dob)

# make dataset with a few variables to summarize
vaccine_vad2 <- vaccine_vad %>% 
  filter(vyear >= 2017 & vyear <= 2020) %>%
  select(vyear, vmonth, vacdate, byear, bmonth, vdelay, vacname2)

# summarize the data with gt_summary package

memory.limit(size=150000)

vaccine_sum <- vaccine_vad2 %>%
  select(byear, bmonth, vdelay, vacname2) %>%
  mutate(bmonth=factor(bmonth)) %>%
  tbl_summary(.,
              by = byear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**All vaccines**") %>% # update the column header
  bold_labels()

vaccine_sum2 <- vaccine_vad2 %>%
  select(vyear, vmonth, vdelay, vacname2) %>%
  mutate(vmonth=factor(vmonth)) %>%
  tbl_summary(.,
              by = vyear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**All vaccines**") %>% # update the column header
  bold_labels()

measle_sum <- vaccine_vad2 %>%
  filter(vacname2=="Measle") %>%
  select(byear, bmonth, vdelay) %>%
  mutate(bmonth=factor(bmonth)) %>%
  tbl_summary(.,
              by = byear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**Measle**") %>% # update the column header
  bold_labels()

measle_sum2 <- vaccine_vad2 %>%
  filter(vacname2=="Measle") %>%
  select(vyear, vmonth, vdelay) %>%
  mutate(vmonth=factor(vmonth)) %>%
  tbl_summary(.,
              by = vyear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**Measle**") %>% # update the column header
  bold_labels()

measle_rubella_sum <- vaccine_vad2 %>%
  filter(vacname2=="Measle_Rubella") %>%
  select(byear, bmonth, vdelay) %>%
  mutate(bmonth=factor(bmonth)) %>%
  tbl_summary(.,
              by = byear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**Measle_Rubella**") %>% # update the column header
  bold_labels()

measle_rubella_sum2 <- vaccine_vad2 %>%
  filter(vacname2=="Measle_Rubella") %>%
  select(vyear, vmonth, vdelay) %>%
  mutate(vmonth=factor(vmonth)) %>%
  tbl_summary(.,
              by = vyear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**Measle_Rubella**") %>% # update the column header
  bold_labels()

dpt_sum <- vaccine_vad2 %>%
  filter(vacname2=="DPT") %>%
  select(byear, bmonth, vdelay) %>%
  mutate(bmonth=factor(bmonth)) %>%
  tbl_summary(.,
              by = byear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**DPT**") %>% # update the column header
  bold_labels()

dpt_sum2 <- vaccine_vad2 %>%
  filter(vacname2=="DPT") %>%
  select(vyear, vmonth, vdelay) %>%
  mutate(vmonth=factor(vmonth)) %>%
  tbl_summary(.,
              by = vyear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**DPT**") %>% # update the column header
  bold_labels()

hepbn_sum <- vaccine_vad2 %>%
  filter(vacname2=="HepBN") %>%
  select(byear, bmonth, vdelay) %>%
  mutate(bmonth=factor(bmonth)) %>%
  tbl_summary(.,
              by = byear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**HepBN**") %>% # update the column header
  bold_labels()

hepbn_sum2 <- vaccine_vad2 %>%
  filter(vacname2=="HepBN") %>%
  select(vyear, vmonth, vdelay) %>%
  mutate(vmonth=factor(vmonth)) %>%
  tbl_summary(.,
              by = vyear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**HepBN**") %>% # update the column header
  bold_labels()

bcg_sum <- vaccine_vad2 %>%
  filter(vacname2=="BCG") %>%
  select(byear, bmonth, vdelay) %>%
  mutate(bmonth=factor(bmonth)) %>%
  tbl_summary(.,
              by = byear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**BCG**") %>% # update the column header
  bold_labels()

bcg_sum2 <- vaccine_vad2 %>%
  filter(vacname2=="BCG") %>%
  select(vyear, vmonth, vdelay) %>%
  mutate(vmonth=factor(vmonth)) %>%
  tbl_summary(.,
              by = vyear, # split table by group
              percent = "col",
              missing = "no" # don't list missing data separately
              ) %>%
  add_n() %>% # add column with total number of non-missing observations
  modify_header(label = "**BCG**") %>% # update the column header
  bold_labels()

vaccine_sum
vaccine_sum2
measle_sum
measle_sum2
measle_rubella_sum
measle_rubella_sum2
dpt_sum
dpt_sum2
hepbn_sum
hepbn_sum2
bcg_sum
bcg_sum2
```

