---
title: "Data Exploration"
date: ' 2020-01-29 (update: `r Sys.Date()`)'
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_float: yes
    keep_md: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r}
knitr::opts_chunk$set()

library(workflowr)
library(data.table)
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggplot2)
library(gt)
library(gtsummary)
library(ggridges)
```

## Quick look at individuals

```{r}
error_datetime <- read.csv(file.path("~", "tuann349_vad", "error_datetime.csv")) %>% as.data.frame()
error_duplicate <- read.csv(file.path("~", "tuann349_vad", "error_duplicate.csv")) %>% as.data.frame()
rm(list = ls(all.names = TRUE))
dtadir <- file.path("~", "sharefolder", "data", "tuann349")
publicProvinces <- list.dirs(dtadir, full.names = F, recursive = F)
publicProvinces <- stringi::stri_trans_general(publicProvinces, "any-ascii")

# individual_private <- readRDS(file = file.path("~", "tuann349_vad", "individual_private.rds"))
# 
# individual_private$year <- year(individual_private$dob)
# individual_private$month <- month(individual_private$dob)
# individual_private$week <- week(individual_private$dob)
# 
# library(operators)
# individual_private_south <- individual_private[individual_private$year >= 2017 & individual_private$year <= 2020 & individual_private$province %!in% publicProvinces]
# 
# individual_private_south_overall <- individual_private_south[, .N, by = .(year, month)]
# individual_private_south_overall2 <- individual_private_south[, .N, by = .(year, month, week)]
# individual_private_south_province <- individual_private_south[, .N, by = .(year, month, province)]
# individual_private_south_province2 <- individual_private_south[, .N, by = .(year, month, week, province)]
# individual_private_south_sex <- individual_private_south[, .N, by = .(year, month, sex)]
# individual_private_south_sex2 <- individual_private_south[, .N, by = .(year, month, week, sex)]
# individual_private_south_province_sex <- individual_private_south[, .N, by = .(year, month, province, sex)]
# individual_private_south_province_sex2 <- individual_private_south[, .N, by = .(year, month, week, province, sex)]
# 
# save(individual_private_south_overall, individual_private_south_province, individual_private_south_sex, individual_private_south_province_sex, file = file.path("~", "updated_dataset", "individual_private_south.Rdata"))
# 
# tab_individual_private_south_sum <- tbl_summary(individual_private_south[, .(province, sex, factor(year))])
# 
# save(tab_individual_private_south_sum, file = file.path("~", "updated_dataset", "tab_individual_private_south.Rdata"))
```

## Quick look at vaccine shots

```{r}
vaccine_vad_private <- readRDS(file = file.path("~", "updated_dataset", "vaccine_vad_private.rds"))
```

All vaccines in private dataset
```{r}
unique(vaccine_vad_private$vacname2)
```

Select vaccines that are consistent to public
```{r}
vacs <- as.data.table(
  rbind(
    cbind(public = "BCG",            private = "BCG"),
    cbind(public = "HepBN",          private = "HepB"),
    cbind(public = "DPT_HepB_Hib",   private = c("DPT_Hib", "DPT_Polio", "DPT_Polio_Hib", "DPT_Polio_HepB_Hib")),
    cbind(public = "OPV",            private = NA),
    cbind(public = "IPV",            private = "IPV"),
    cbind(public = "Measle",         private = c("Measle", "Measle_Mumps_Rubella", "Measle_Rubella")),
    cbind(public = "DPT",            private = "DPT"),
    cbind(public = "JEV",            private = "JEV"),
    cbind(public = "Td",             private = "Td")
  )
)
# Get a vectors of the private vaccines that have the same type in public
vacnames <- vacs$private[!is.na(vacs$private)]
vacs
```

```{r}
# Children, private provinces and same vaccine as public
vaccine_vad_private_south <- vaccine_vad_private[vaccine_vad_private$year >= 2017 &
                                                   vaccine_vad_private$year <= 2020 &
                                                   !(vaccine_vad_private$province %in% publicProvinces) &
                                                   vaccine_vad_private$vacname2 %in% vacnames]

# vaccine_overall_private_south <- vaccine_vad_private_south[, .N, by = .(vyear, vmonth)]
# vaccine_overall_private_south2 <- vaccine_vad_private_south[, .N, by = .(vyear, vmonth, vweek)]
# 
# vaccine_schedule_private_south <- vaccine_vad_private_south[, .N, by = .(vsyear, vsmonth)]
# vaccine_schedule_private_south2 <- vaccine_vad_private_south[, .N, by = .(vsyear, vsmonth, vsweek)]
# 
# vaccine_province_private_south <- vaccine_vad_private_south[, .N, by = .(vyear, vmonth, province)]
# 
# vaccine_vacname_private_south <- vaccine_vad_private_south[, .N, by = .(vyear, vmonth, vacname2)]
# #vaccine_vacname_private2 <- vaccine_vad_private[, .N, by = .(vyear, vmonth, vweek, vacname2)]
# 
# vaccine_province_vacname_private_south <- vaccine_vad_private_south[, .N, by = .(vyear, vmonth, province, vacname2)]
# #vaccine_province_vacname_private2 <- vaccine_vad_private[, .N, by = .(vyear, vmonth, vweek, province, vacname2)]
# 
# save(vaccine_overall_private_south, vaccine_province_private_south, vaccine_vacname_private_south, vaccine_province_vacname_private_south, file = file.path("~", "updated_dataset", "vaccine_private_south.Rdata"))
# 
# tab_vac_sum_private_south <- tbl_summary(vaccine_vad_private_south[, .(province, vacname2, factor(vyear))])
# save(tab_vac_sum_private_south, file = file.path("~", "updated_dataset", "tab_vaccine_private_south.Rdata"))
rm(list=c("vaccine_vad_private"))
gc()
```

```{r}
load(file.path("~", "updated_dataset", "vaccine_private_south.Rdata"))
load(file.path("~", "updated_dataset", "tab_vaccine_private_south.Rdata"))

load(file.path("~", "updated_dataset", "individual_private_south.Rdata"))
load(file.path("~", "updated_dataset", "tab_individual_private_south.Rdata"))
```

### Descriptive table

```{r}
t1 <- vaccine_vad_private_south %>% 
  mutate(age=2021-as.numeric(year)
         # agegr=NA,
         # agegr=ifelse(age>=0 & age<=10, 1, 
         #              ifelse(age>10 & age<=20, 2,
         #                      ifelse(age>20 & age<=30, 3, 
         #                             ifelse(age>30 & age<=40, 4, 
         #                                    ifelse(age>40 & age<=50, 5, 
         #                                           ifelse(age>50, 6, agegr)))))
         #                 ),
         # agegr=factor(agegr, levels = c(1,2,3,4,5,6), labels = c("0-10", "11-20", "21-30", "31-40", "41-50", "> 50")),
         # yeargr=NA,
         # yeargr=ifelse(year>=1969 & year<=1980, 1, 
         #               ifelse(year>1980 & year<=1990, 2, 
         #                      ifelse(year>1990 & year<=2000, 3, 
         #                             ifelse(year>2000 & year<=2010, 4, 
         #                                    ifelse(year>2010 & year<=2020, 5, yeargr))))
         #               ),
         # yeargr=factor(yeargr, levels = c(1,2,3,4,5), labels = c("1969-1980", "1981-1990", "1991-2000", "2001-2010","2011-2020"))
         ) %>%
  dplyr::select(age, sex, province) %>%
  tbl_summary(
  #by=type, # split table by group
  percent = "column",
  missing = "no" # don't list missing data separately
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  #add_p(pvalue_fun=~style_pvalue(.x,digits=2)) %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
t1
```

### Overall

```{r}
ggplot(data = vaccine_overall_private_south, aes(x = factor(vmonth), y = N/1000, color = factor(vyear))) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point(size = 3) +
  geom_line(aes(group = vyear), size = 1.5) +
  scale_x_discrete(name = "Month") +
  geom_smooth() +
  stat_smooth(method="loess", formula = y ~ x, colour="blue", size=1.5) +
  scale_y_continuous(name = "Number of shot (x 10^3)", breaks = seq(from = 50, to = 1600, by = 100)) +
  scale_color_discrete(name = "Year") +
  theme_bw() +
  ggtitle("Total number of vaccination shots by month and year at private clinics")
# ggsave(filename = file.path("..", "figures", "vaccine_month_year_private_south.png"), width = 7, height = 5)
```

```{r}
ggplot(vaccine_overall_private_south, aes(vmonth, N/1000, color = factor(vyear))) +
  geom_point(size=3) +
  geom_line(aes(group=vyear)) +
  geom_smooth () + 
  stat_smooth(method="loess", formula = y ~ x, colour="blue", size=1) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot (x 10^3)") +
  scale_color_discrete(name = "Year") +
  theme_bw() +
  ggtitle("Total number of vaccination shots by month and year at private clinics") +
  facet_wrap(~ vyear, scale = "free_y")
# ggsave(filename = file.path("..", "figures", "vaccine_month_year_private_south2.png"), width = 7, height = 5)
```

### By province

```{r}
ggplot(data = vaccine_province_private_south, aes(x = factor(vmonth), y = N/1000, color = factor(vyear))) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point() +
  geom_line(aes(group = vyear)) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot (x 10^3)") +
  scale_color_discrete(name = "Year") +
  facet_wrap(~ province, scale = "free_y") +
  theme_bw() +
  theme(legend.position = "bottom") +
  ggtitle("Number of vaccination shot in each province by month and year at private clinics")
# ggsave(filename = file.path("..", "figures", "vaccine_province_year_private_south.png"), width = 10, height = 7)
```

### By vaccine

```{r}
ggplot(data = vaccine_vacname_private_south[!is.na(vacname2)], aes(x = factor(vmonth), y = N/1000)) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point(aes(color = factor(vyear))) +
  geom_line(aes(group = vyear, color = factor(vyear))) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot (x 10^3)") +
  scale_color_discrete(name = "Year") +
  facet_wrap(~ vacname2, scale = "free_y") +
  theme_bw() +
  theme(legend.position = "bottom") +
  ggtitle("Total number of shots of each vaccine at private clinics by month and year")
# ggsave(filename = file.path("..", "figures", "vaccine_month_year_vaccine_private_south.png"), width = 10, height = 7)
```

```{r}
ggplot(data = vaccine_vacname_private_south[!is.na(vacname2)], aes(x = reorder(vacname2, N/1000, decreasing=T), y = N/1000)) +
  #geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_bar(stat = "identity", fill="red", width = 0.75) +
  #geom_text(aes(label = N/1000, y = N/1000 + 10), size = 3) +
  scale_x_discrete(name = NULL) +
  scale_y_continuous(name = "Number of shot (x 10^3)") +
  scale_color_discrete(name = "Year") +
  facet_wrap(~ vyear, scale = "free_y") +
  theme_bw() +
  theme(axis.text.y = element_text(size = 6),
        panel.grid.major = element_blank()) + coord_flip() +
  ggtitle("Total number of shots at private clinics by vaccine and year")
# ggsave(filename = file.path("..", "figures", "vaccine_year_vaccine_private_south.png"), width = 10, height = 7)
```
