---
title: "Data Exploration"
date: ' 2020-01-29 (update: `r Sys.Date()`)'
output:
  html_document:
    theme: cerulean
    toc: yes
    toc_float: yes
    keep_md: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r}
knitr::opts_chunk$set()

library(workflowr)
library(data.table)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(gt)
library(gtsummary)
library(ggridges)
```

### Measle

```{r}
measle_private <- readRDS(file = file.path("..", "..", "tuann349_vad", "measle_private.rds"))

mea_private <- measle_private[, .N, by = .(vyear, vmonth)]
mea_private2 <- measle_private[, .N, by = .(vyear, vmonth, vweek)]
#mea_private_delay <- measle_private[, .N, by = .(vyear, vmonth, vdelayd, vacname2)]
```

#### Overall

```{r}
ggplot(data = mea_private[vyear >= 2017 & vyear <= 2020], aes(x = factor(vmonth), y = N/1000, color = factor(vyear))) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point(size = 3) +
  geom_line(aes(group = vyear), size = 1.5) +
  scale_x_discrete(name = "Month") +
  geom_smooth() +
  stat_smooth(method="loess", formula = y ~ x, colour="blue", size=1.5) +
  scale_y_continuous(name = "Number of shot (x 10^3)", breaks = seq(from = 0, to = 200, by = 50)) +
  scale_color_discrete(name = "Year") +
  theme_bw() +
  ggtitle("Total number of Measle vaccination shot by month and year")
#ggsave(filename = file.path("figures", "measle_month_year.png"), width = 7, height = 5)
```

```{r}
ggplot(mea_private[vyear >= 2017 & vyear <= 2020], aes(vmonth, N/1000, color = factor(vyear))) +
  geom_point(size=3) +
  geom_line(aes(group=vyear)) +
  geom_smooth () + 
  stat_smooth(method="loess", formula = y ~ x, colour="blue", size=1) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot (x 10^3)", breaks = seq(from = 0, to = 200, by = 50)) +
  scale_color_discrete(name = "Year") +
  theme_bw() +
  ggtitle("Total number of Measle vaccination shot by month and year") +
  facet_wrap(~ vyear, scale = "free_y")
#ggsave(filename = file.path("figures", "measle_month_year2.png"), width = 7, height = 5)
```

#### Delays in vaccination (months)

```{r}
ggplot(data = measle_private[year>= 2017 & year <= 2020 & vdelay>=0], aes(x = vdelay, y = factor(month), color = factor(year))) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none") +
  facet_grid(vacname2~year, scale = "free_y") +
  labs(y = "Birth months", x="Duration of delays in Measle vaccination (months)") +
  scale_color_discrete(name = "Year") +
  ggtitle("Delays in Measle vaccination (months) for children born 2017-2020")
#ggsave(filename = file.path("figures", "measle_delay_year4.png"), width = 7, height = 5)
```

```{r}
#load(file.path("..", "..", "tuann349_vad", "vacinfo.Rdata"))
#load(file.path("..", "..", "tuann349_vad", "vacinfo_private.Rdata"))

measle_private_delay <- measle_private %>%
  select(pid, province, district, commune, sex, dob, vacname2, epi, msl, start, shot, vacdate, vyear, vmonth, year, month, vagem, vagem2, vdelay, vsche, vsyear, vsmonth, vdelayd) %>% filter(year>=2017 & year<=2021) %>%
  mutate(vdelay_outcome=ifelse(vdelay>0,1,0),
         age=2021-year,
         sex=as.numeric(sex),
         sex=recode(sex, "0"="0", "1"="1", "2"="1"),
         sex=factor(sex, levels=c(0,1), labels=c("F","M")),
         shot=factor(shot),
         vacdate_f=ifelse(vacdate<"2020-04-01",0,1),
         vacdate_f=factor(vacdate_f, levels = c(0,1), labels = c("Before", "After"))) %>% 
  filter(province!="Tinh tap huan")
```

```{r}
t1 <- measle_private_delay %>% select(age, sex, province, vacname2, shot, vacdate_f, vdelay, vdelay_outcome) %>% 
  tbl_summary(
  by=vdelay_outcome, # split table by group
  percent = "row",
  missing = "no" # don't list missing data separately
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p(pvalue_fun=~style_pvalue(.x,digits=2)) %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
t1
```

```{r}
#install.packages("rms")
library("rms")
theme_set(theme_bw())
dd <- datadist(measle_private_delay)
options(datadist="dd")
dd

fit1 <- lrm(vdelay_outcome~age, data=measle_private_delay)
anova(fit1)
pred <- Predict(fit1, age=1:4, fun=plogis)
ggplot(pred, ylab=expression(paste(hat(P),"(delay)")), ylim=c(0,1)) +
  #scale_x_discrete(name = "Age") + 
  theme(text = element_text(size=15), axis.text.x = element_text(size=14), axis.text.y = element_text(size=14), legend.text=element_text(size=14)) +
  geom_line(size=1.25) + 
  geom_ribbon(aes(ymin = pred$lower, ymax = pred$upper), alpha=0.05) + 
  annotate("text", x=3.5, y=0.8, label=paste0("p-value<0.0001"), parse = TRUE)
```

```{r}
fit2 <- lrm(vdelay_outcome~sex, data=measle_private_delay)
anova(fit2)
pred <- Predict(fit2, sex=NA, fun=plogis)
ggplot(pred)

ggplot(pred, ylab=expression(paste(hat(P),"(delay)")))
```

```{r}
fit3 <- lrm(vdelay_outcome~province, data=measle_private_delay)
anova(fit3)
pred <- Predict(fit3, province=NA, fun=plogis)
ggplot(pred, ylab=expression(paste(hat(P),"(delay)")))
```

```{r}
fit4 <- lrm(vdelay_outcome~vacdate_f, data=measle_private_delay)
anova(fit4)
pred <- Predict(fit4, vacdate_f=NA, fun=plogis)
ggplot(pred, ylab=expression(paste(hat(P),"(delay)")))
```
```{r}
fit5 <- lrm(vdelay_outcome~district, data=measle_private_delay)
#anova(fit5)
pred <- Predict(fit5, district=NA, fun=plogis)
ggplot(pred, ylab=expression(paste(hat(P),"(delay)")))
```
