---
title: "Report"
date: " 2020-02-21 (update: `r Sys.Date()`)"
output:
    html_document:
      theme: cerulean
      toc: yes
      toc_float: yes
editor_options:
  chunk_output_type: console
---

```{r}
library(data.table)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(gt)
library(gtsummary)
```

## Overview of vaccination in Vietnam

## Methods 

### Dataset 

```{r}
load(file.path("..", "tuann349_vad", "vaccine.Rdata"))
```

```{r}
gt(vaccine_sum$province[order(-N)])
```

```{r}
gt(vaccine_sum$vacname[order(-N)])
```

```{r}
gt(vaccine_sum$year[order(vyear)])
```

## Overview

```{r}
ggplot(data = vaccine_overall, aes(x = factor(vmonth), y = N/1000, color = factor(vyear))) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point(size = 3) +
  geom_line(aes(group = vyear), size = 1.5) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot (x 10^3)", breaks = seq(from = 50, to = 1100, by = 100)) +
  scale_color_discrete(name = "Year") +
  theme_bw() +
  ggtitle("Total number of vaccination shot by month and year")
ggsave(filename = file.path("figures", "vaccine_month_year.png"), width = 7, height = 5)
```

### By province

```{r}
ggplot(data = vaccine_province, aes(x = factor(vmonth), y = N/1000, color = factor(vyear))) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point() +
  geom_line(aes(group = vyear)) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot (x 10^3)") +
  scale_color_discrete(name = "Year") +
  facet_wrap(~ province, scale = "free_y") +
  theme_bw() +
  theme(legend.position = "bottom") +
  ggtitle("Number of vaccination shot in each province by month and year")
ggsave(filename = file.path("figures", "vaccine_month_year_province.png"), width = 10, height = 7)
```

### By vaccine

```{r}
ggplot(data = vaccine_vacname, aes(x = factor(vmonth), y = N)) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point(aes(color = factor(vyear))) +
  geom_line(aes(group = vyear, color = factor(vyear))) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot") +
  scale_color_discrete(name = "Year") +
  facet_wrap(~ vacname2, scale = "free_y") +
  theme_bw() +
  theme(legend.position = "bottom") +
  ggtitle("Number of shot of each vaccine by month and year")
ggsave(filename = file.path("figures", "vaccine_month_year_vaccine.png"), width = 10, height = 7)
```

### In Cao Bang, Ha Noi and Nghe An by vaccine

```{r}
ggplot(data = vaccine_province_vacname[vyear <= 2020 & province %in% c("Cao Bang", "Ha Noi", "Nghe An")], aes(x = factor(vmonth), y = N)) +
  geom_rect(aes(xmin = 3, xmax = 5, ymin = -Inf, ymax = Inf), fill = "grey80", color = "grey90", alpha = 0.015) +
  geom_point(aes(color = factor(vacname2))) +
  geom_line(aes(group = vacname2, color = factor(vacname2))) +
  scale_x_discrete(name = "Month") +
  scale_y_continuous(name = "Number of shot") +
  scale_color_discrete(name = "Name of vaccine") +
  facet_grid(province ~ vyear, scale = "free_y") +
  theme_bw() +
  theme(legend.position = "bottom") +
  ggtitle("Number of shot of each vaccine by province and time")
ggsave(filename = file.path("figures", "vaccine_month_year_vaccine_CB_HN_NA.png"), width = 10, height = 7)
```

## Vaccination during 2017-2019

### Vaccine coverage

### Specific vaccines

#### BCG

#### Hepatitis B

#### Diptheria

#### Measle

## Vaccination since 2020

### Vaccine coverage

### Specific vaccines

#### BCG

#### Hepatitis B

#### Diptheria

#### Measle

## Summary

## Conclusion


