---
title: "Calculate number of births with GSO data"
author: "Thinh Ong"
date: "2/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Read and clean data
```{r warning=FALSE}
pj <- "~/Vaccination_COVID"
birthDeath <- read.table(file.path(pj, "data", "VN_birth_death_year.csv"),
                         header = T, sep = ";")
pop <- read.table(file.path(pj, "data", "VN_popsize_year_2.csv"),
                   header = T, sep = ";", skipNul = TRUE)

# Birth data
birth <- birthDeath[,c(1, grep("birth", colnames(birthDeath)))]
colnames(birth) <- c("province", "birthRate17", "birthRate18", "birthRate19", "birthRate20")
birth[,-1] <- sapply(birth[,-1], as.numeric)

# Death data
death <- birthDeath[,c(1, grep("death", colnames(birthDeath)))]
colnames(death) <- c("province", "deathRate17", "deathRate18", "deathRate19", "deathRate20")
death[,-1] <- sapply(death[,-1], as.numeric)

# Population data
colnames(pop) <- c("province", "pop17", "pop18", "pop19", "pop20")
pop[,-1] <- sapply(pop[,-1], as.numeric)
```

# Population data
```{r}
head(pop, 8)
```

# Birth rate data
```{r}
head(birth, 8)
```

Quickly see how many births per year among the whole country
```{r}
whole <- pop[1,-1] * birth[1,-1]
colnames(whole) <- gsub("pop", "birth", colnames(whole))
whole
```

Only keep provinces data and merge data
```{r}
exRow <- "WHOLE|Delta|area|Ha Tay|South|Central Highlands"
birth <- birth[!grepl(exRow, birth$province),]
death <- death[!grepl(exRow, death$province),]
pop <- pop[!grepl(exRow, pop$province),]
df <- merge(birth, death, by = "province")
df <- merge(df, pop, by = "province")
```

# Calculate number of birth, death
```{r}
birthRates <- grep("birth", colnames(df), value = T)
deathRates <- grep("death", colnames(df), value = T)
births <- gsub("Rate", "", birthRates)
deaths <- gsub("Rate", "", deathRates)
pops <- grep("pop", colnames(df), value = T)
errs <- gsub("pop", "err", pops)
# CBR = 1000 * Birth / Pop => Birth = Pop * CBR / 1000
# CDR = 1000 * Death / Pop => Death = Pop * CDR / 1000
for (i in 1:length(birthRates)) {
  df[,births[i]] <- df[,pops[i]] * df[,birthRates[i]]
  df[,deaths[i]] <- df[,pops[i]] * df[,deathRates[i]]
  if (i > 1) {
    df[,errs[i - 1]] <- df[,pops[i]] * 1000 - (df[,pops[i - 1]] * 1000 + df[,births[i]] - df[,deaths[i]])
  }
}

# Display sum birth from 2017-2020
df$birth17_20 <- rowSums(df[,c("birth17", "birth18", "birth19", "birth20")])

dtadir <- file.path("~", "sharefolder", "data", "tuann349")
publicProvinces <- list.dirs(dtadir, full.names = F, recursive = F)
publicProvinces <- stringi::stri_trans_general(publicProvinces, "any-ascii")

sum(df$birth17_20[df$province %in% publicProvinces])
knitr::kable(df[df$province %in% publicProvinces, c("province", "birth17_20")])
```

# Compare to whole country data
Compare sum of all births from provinces and the number calculated by whole country data
```{r}
allBirths <- data.frame(t(colSums(df[,births])))
whole <- rbind(whole, allBirths)
rownames(whole) <- c("whole", "sumProvinces")
whole
```

```{r}

```
