---
title: "Discussion on 05/04/2022"
author: "Duc Du, Thinh Ong"
date: ' `r Sys.Date()`'
output:
  workflowr::wflow_html:
    toc: true
    theme: cosmo
  pdf_document:
    toc: yes
  html_document:
    theme: cerulean
    toc: yes
    toc_float: yes
    keep_md: yes
  word_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---

```{r}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache.lazy = FALSE, tidy.opts=list(width.cutoff=60), tidy=TRUE, root.dir = rprojroot::find_rstudio_root_file())

library(data.table)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(gtsummary)
library(ggsci)

# Path to dataset
allp <- file.path("~", "updated_dataset")
outp <- file.path("~", "figs")

# Load vector of public provinces names
publicProvinces <- readRDS("~/Vaccination_COVID/data/publicProvinces.rds")
```

Load and process measles dataset

```{r}
# Load measles data
load(file.path(allp, "measle_all.Rdata"))

# Get children and public provinces only
measle_all <- measle_all[measle_all$province %in% publicProvinces &
                           measle_all$year >= 2017 & measle_all$year <= 2020,]

# Remove duplication: same id, address (province, district, commune), sex, dob, received the same vaccine in the same day (vacname2, vacdate)
measle_all <- measle_all %>%
  distinct(., pid, province, district, commune, sex, dob,
           vacname2, vacdate, .keep_all = TRUE)

# Remove records have the same measles vaccine in 1 day
measle_all <- measle_all %>%
  distinct(., pid, vacdate, .keep_all = T)

# Remove records have dob = vacdate (since this is measles)
measle_all <- measle_all[measle_all$dob != measle_all$vacdate,]

# Grouped by id and vaccine name, sorted by vaccination date, the 1st time they come shot = 1, second time shot = 2...
measle_all <- measle_all %>%
  group_by(pid, vacname2) %>%
  arrange(vacdate) %>%
  mutate(shot = 1:n()) %>%
  ungroup()

# Turn into data table
measle_all <- data.table(measle_all)

# How many shots they got
# table(measle_all$shot)
# 
#       1       2       3       4       5 
# 4211481  295200    2074      34       7 

# Only get people having <= 2 shots
measle_all <- measle_all[measle_all$shot <= 2,]

# table(measle_all$shot)
#       1       2 
# 4211481  295200 

# Clean sex variable
measle_all$sex <- ifelse(measle_all$sex==2, 1, measle_all$sex)
measle_all$sex <- factor(measle_all$sex, levels=c(0,1), labels=c("F","M"))

# Compute age
measle_all$age <- 2021 - measle_all$year
measle_all$vdelaym <- measle_all$vagem2 - measle_all$start

# Expected date of receiving vaccine shots
measle_all$expect_vdate <- measle_all$dob %m+% months(measle_all$start)
measle_all$expect_vyear <- year(measle_all$expect_vdate)
measle_all$expect_vmonth <- month(measle_all$expect_vdate)
```

## All provinces
```{r}
measles_1st <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020),]
```

```{r, fig.height=2, fig.width=8}
df_plot <- measles_1st[measles_1st$expect_vmonth <= 6,]

df_plot$expect_vmonth <- factor(df_plot$expect_vmonth, levels = c(1, 2, 3, 4, 5, 6), labels = c("January", "February", "March", "April", "May", "June"))
df_plot$expect_vyear <- factor(df_plot$expect_vyear)

ggplot(df_plot, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  scale_fill_nejm() +
  coord_cartesian(xlim = c(0, 6)) +
  theme_light() +
  facet_wrap(~ expect_vmonth, scales = "free_y", nrow = 1) +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("Measles") +
  theme(axis.text.y=element_blank())

ggsave(file.path(outp, "allprovinces.pdf"), width = 6, height = 1.7)
```


## Compare before and after lockdown
```{r}
# If children are scheduled in May 2020, we only have data until December 2020 (8 months), we take a cohort of chilren schedule in 

measles_25 <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear == 2020 & 
    (measle_all$expect_vmonth == 2 & measle_all$vyear == 2020 & measle_all$vmonth >= 2 & measle_all$vmonth <= 9) | 
    (measle_all$expect_vmonth == 5 & measle_all$vyear == 2020 & measle_all$vmonth >= 5 & measle_all$vmonth <= 12),]

measles_25$is_delay <- ifelse(measles_25$vdelaym >= 1, 1, 0)
measles_25$is_delay <- factor(measles_25$is_delay)
measles_25$expect_vmonth <- factor(measles_25$expect_vmonth)
measles_25$vacname2 <- factor(measles_25$vacname2)

tb_25 <- measles_25 %>% 
  select(vdelaym, type2, vacname2, expect_vmonth, is_delay) %>%
  tbl_summary(
    by = expect_vmonth,
    percent = "col",
    digits = everything() ~ 2
  ) %>%
  add_p(pvalue_fun=~style_pvalue(.x,digits=2))

tb_25
```


## March

```{r}
df_plot <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020) & measle_all$expect_vmonth == 3,]

df_plot$expect_vmonth <- factor(df_plot$expect_vmonth)
df_plot$expect_vyear <- factor(df_plot$expect_vyear)

# GRDP
# grdp_rank <- c("Ha Noi", "Bac Ninh", "Hai Phong", "Thanh Hoa", "Quang Ninh", "Nghe An", "Hai Duong", "Thai Nguyen", "Vinh Phuc", "Bac Giang", "Thai Binh", "Hung Yen", "Ha Tinh", "Nam Dinh", "Phu Tho", "Son La", "Ninh Binh", "Ha Nam", "Lao Cai", "Hoa Binh", "Lang Son", "Tuyen Quang", "Yen Bai", "Ha Giang", "Dien Bien", "Lai Chau", "Cao Bang", "Bac Kan")
# 
# df_plot$province <- factor(df_plot$province, levels = gdp_rank)
# 
# pop <- readRDS(file.path("~/Vaccination_COVID", "data", "birthGSO.rds"))
pop <- pop[order(pop$pop20, decreasing = T),]
pop$province <- gsub("  ", " ", pop$province)
pop_rank <- pop$province[pop$province %in% publicProvinces]

# GDP
gdp_rank <- c("Bac Giang", "Hai Phong", "Quang Ninh", "Ha Nam", "Lao Cai", "Ninh Binh", "Hung Yen", "Son La", "Thanh Hoa", "Nam Dinh", "Yen Bai", "Tuyen Quang", "Cao Bang", "Nghe An", "Thai Nguyen", "Lai Chau", "Ha Noi", "Hoa Binh", "Phu Tho", "Thai Binh", "Bac Kan", "Vinh Phuc", "Hai Duong", "Lang Son", "Dien Bien", "Ha Giang", "Bac Ninh", "Ha Tinh")

df_plot$province <- factor(df_plot$province, levels = pop_rank)

ggplot(df_plot, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  scale_fill_nejm() +
  theme_light() +
  facet_wrap(~ province, scales = "free") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("All clinics: March") +
  theme(axis.text.y=element_blank())
```

## April

```{r}
df_plot <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020) & measle_all$expect_vmonth == 4,]

df_plot$expect_vmonth <- factor(df_plot$expect_vmonth)
df_plot$expect_vyear <- factor(df_plot$expect_vyear)

df_plot$province <- factor(df_plot$province, levels = gdp_rank)

# df_plot$province <- factor(df_plot$province, levels = pop_rank)

ggplot(df_plot, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  scale_fill_nejm() +
  theme_light() +
  facet_wrap(. ~ province, scales = "free") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("All clinics: April") +
  theme(axis.text.y=element_blank())
```

```{r}
measles_1st <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020) & measle_all$expect_vmonth == 4 & measle_all$type2 == "public",]

ggplot(measles_1st, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  theme_minimal() +
  facet_wrap(. ~ province, scales = "free") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("Public clinics: April") +
  theme(axis.text.y=element_blank())
```

```{r}
measles_1st <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020) & measle_all$expect_vmonth == 4 & measle_all$type2 == "private",]

ggplot(measles_1st, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  theme_minimal() +
  facet_wrap(. ~ province, scales = "free") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("Private clinics: April") +
  theme(axis.text.y=element_blank())
```

## May

```{r}
df_plot <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020) & measle_all$expect_vmonth == 5,]

df_plot$expect_vyear <- factor(df_plot$expect_vyear)

ggplot(df_plot, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  scale_fill_nejm() +
  theme_light() +
  facet_wrap(. ~ province, scales = "free") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("All clinics: May") +
  theme(axis.text.y=element_blank())
```

```{r}
measles_1st <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020) & measle_all$expect_vmonth == 5 & measle_all$type2 == "public",]

ggplot(measles_1st, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  theme_minimal() +
  facet_wrap(. ~ province, scales = "free") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("Public clinics: May") +
  theme(axis.text.y=element_blank())
```

```{r}
measles_1st <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020) & measle_all$expect_vmonth == 5 & measle_all$type2 == "private",]

ggplot(measles_1st, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  theme_minimal() +
  facet_wrap(. ~ province, scales = "free") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("Private clinics: May") +
  theme(axis.text.y=element_blank())
```

## June

```{r}
measles_1st <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020) & measle_all$expect_vmonth == 6,]

ggplot(measles_1st, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  theme_minimal() +
  facet_wrap(. ~ province, scales = "free") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("All clinics: June") +
  theme(axis.text.y=element_blank())
```

```{r}
measles_1st <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020) & measle_all$expect_vmonth == 6 & measle_all$type2 == "public",]

ggplot(measles_1st, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  theme_minimal() +
  facet_wrap(. ~ province, scales = "free") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("Public clinics: June") +
  theme(axis.text.y=element_blank())
```

```{r}
measles_1st <- measle_all[measle_all$shot == 1 & measle_all$expect_vyear %in% c(2019, 2020) & measle_all$expect_vmonth == 6 & measle_all$type2 == "private",]

ggplot(measles_1st, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  theme_minimal() +
  facet_wrap(. ~ province, scales = "free") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  ggtitle("Private clinics: June") +
  theme(axis.text.y=element_blank())
```

## Plot 6 representative provinces
```{r, fig.height=5, fig.width=8}
prov_levels <- c("Ha Noi", "Bac Giang", "Son La", "Nghe An", "Lai Chau", "Yen Bai")

df_plot <- measle_all[measle_all$shot == 1 & 
                        measle_all$expect_vyear %in% c(2019, 2020) & 
                        measle_all$expect_vmonth %in% c(3, 4, 5, 6) &
                        measle_all$province %in% prov_levels,]

df_plot$expect_vmonth <- factor(df_plot$expect_vmonth, levels = c(3, 4, 5, 6), labels = c("March", "April", "May", "June"))
df_plot$expect_vyear <- factor(df_plot$expect_vyear)
df_plot$province <- factor(df_plot$province, levels = prov_levels)

ggplot(df_plot, aes(x = vdelaym, group = expect_vyear, fill = expect_vyear)) +
  geom_density(alpha = 0.5) +
  coord_cartesian(xlim = c(0, 6)) +
  scale_fill_nejm() +
  theme_light() +
  facet_grid(cols = vars(province), rows = vars(expect_vmonth), scales = "free", switch = "y") +
  labs(y = NULL, x = "Delay (months)", fill = "Year") +
  theme(axis.text.y=element_blank(), strip.placement = "outside")

ggsave(file.path(outp, "provinces_month.pdf"), width = 6, height = 4)
```

## Bar chart
```{r}
# Get a cohort of 6-month children who scheduled to receive measles from January to June 2019 and 2020
df <- measle_all[measle_all$shot == 1 & 
    ((measle_all$expect_vyear == 2019 &
    ((measle_all$expect_vmonth == 1 & measle_all$vyear == 2019 & measle_all$vmonth >= 2 & measle_all$vmonth <= 7) |
    (measle_all$expect_vmonth == 2 & measle_all$vyear == 2019 & measle_all$vmonth >= 2 & measle_all$vmonth <= 8) | 
    (measle_all$expect_vmonth == 3 & measle_all$vyear == 2019 & measle_all$vmonth >= 3 & measle_all$vmonth <= 9) | 
    (measle_all$expect_vmonth == 4 & measle_all$vyear == 2019 & measle_all$vmonth >= 4 & measle_all$vmonth <= 10) | 
    (measle_all$expect_vmonth == 5 & measle_all$vyear == 2019 & measle_all$vmonth >= 5 & measle_all$vmonth <= 11)|
    (measle_all$expect_vmonth == 6 & measle_all$vyear == 2019 & measle_all$vmonth >= 5 & measle_all$vmonth <= 12))) |
    (measle_all$expect_vyear == 2020 &
    ((measle_all$expect_vmonth == 1 & measle_all$vyear == 2020 & measle_all$vmonth >= 2 & measle_all$vmonth <= 7) | 
    (measle_all$expect_vmonth == 2 & measle_all$vyear == 2020 & measle_all$vmonth >= 2 & measle_all$vmonth <= 8) | 
    (measle_all$expect_vmonth == 3 & measle_all$vyear == 2020 & measle_all$vmonth >= 3 & measle_all$vmonth <= 9) | 
    (measle_all$expect_vmonth == 4 & measle_all$vyear == 2020 & measle_all$vmonth >= 4 & measle_all$vmonth <= 10) | 
    (measle_all$expect_vmonth == 5 & measle_all$vyear == 2020 & measle_all$vmonth >= 5 & measle_all$vmonth <= 11) |
    (measle_all$expect_vmonth == 6 & measle_all$vyear == 2020 & measle_all$vmonth >= 5 & measle_all$vmonth <= 12)))),]

df$is_delay <- ifelse(df$vdelaym > 1, "Delay", "Not delay")
df$is_delay <- factor(df$is_delay)

df_plot <- df %>% count(expect_vyear, expect_vmonth, is_delay) %>% group_by(expect_vyear, expect_vmonth) %>% mutate(prop = n / sum(n))

df_plot$prop <- ifelse(df_plot$expect_vyear == 2019, df_plot$prop * (-1), df_plot$prop)
df_plot$expect_vyear <- factor(df_plot$expect_vyear)

df_plot <- df_plot[df_plot$is_delay == "Delay",]
df_plot$expect_vmonth <- factor(df_plot$expect_vmonth, levels = c(6, 5, 4, 3, 2, 1), labels = c("June", "May", "April", "March", "February", "January"))

ggplot(df_plot, aes(x = expect_vmonth, y = prop, fill = expect_vyear)) +
  geom_bar(stat = "identity") + 
  geom_text(aes(label = sprintf("%.1f", ifelse(prop >= 0, 100 * prop, -100 * prop)),
                hjust = ifelse(prop >= 0, -0.2, 1.2))) + 
  scale_y_continuous(expand = expansion(mult = 0.2)) +
  coord_flip() +
  scale_fill_nejm() +
  labs(x = NULL, y = NULL, fill = "Year") +
  theme_light() +
  theme(axis.text.y = element_text(size = 13),
        axis.text.x = element_blank(),
        legend.position = "none")

ggsave(file.path(outp, "bar_1920.pdf"), width = 4.5, height = 2)
```

```{r}
measles_19 <- measle_all[measle_all$expect_vyear == 2019,]

measles_19$less_1m <- ifelse(measles_19$vdelaym <= 1, 1, 0)
measles_19$from_1m_2m <- ifelse(measles_19$vdelaym > 1 & measles_19$vdelaym <= 2, 1, 0)

df_m19 <- measles_19 %>% count(expect_vyear, expect_vmonth, less_1m) %>% group_by(expect_vyear, expect_vmonth) %>% mutate(prop = 100 * n / sum(n))
df_m19 <- df_m19[df_m19$less_1m == 1,]
mean(df_m19$prop)
sd(df_m19$prop)

df_m19 <- measles_19 %>% count(expect_vyear, expect_vmonth, from_1m_2m) %>% group_by(expect_vyear, expect_vmonth) %>% mutate(prop = 100 * n / sum(n))
df_m19 <- df_m19[df_m19$from_1m_2m == 1,]
mean(df_m19$prop)
sd(df_m19$prop)

measles_20 <- measle_all[measle_all$expect_vyear == 2020,]

measles_20$less_1m <- ifelse(measles_20$vdelaym <= 1, 1, 0)
measles_20$from_1m_2m <- ifelse(measles_20$vdelaym > 1 & measles_20$vdelaym <= 2, 1, 0)

df_m20 <- measles_20 %>% count(expect_vyear, expect_vmonth, less_1m) %>% group_by(expect_vyear, expect_vmonth) %>% mutate(prop = 100 * n / sum(n))
df_m20 <- df_m20[df_m20$less_1m == 1,]
mean(df_m20$prop)
sd(df_m20$prop)

df_m20 <- measles_20 %>% count(expect_vyear, expect_vmonth, from_1m_2m) %>% group_by(expect_vyear, expect_vmonth) %>% mutate(prop = 100 * n / sum(n))
df_m20 <- df_m20[df_m20$from_1m_2m == 1,]
mean(df_m20$prop)
sd(df_m20$prop)

```

